### ISSUE TITLE
com.karuslabs.commons 4.8.0-SNAPSHOT maven-metadata.xml not found!

### ISSUE THREAD

**Issue by XjCyan1de** [Pante/Chimera#220]
![image](https://user-images.githubusercontent.com/18630111/93001695-a6e22180-f539-11ea-8a45-0cfd7f280465.png)

![image](https://user-images.githubusercontent.com/18630111/93001700-ae092f80-f539-11ea-8e38-cccf78c4175a.png)

**Comment by Pante** [comment]
Using both GitHub & Travis CI is a bad idea.
