### ISSUE TITLE
[BUG] `StringArgumentType.word()` does not support non-ASCII characters

### ISSUE THREAD

**Issue by StepanovIgorS** [Pante/chimera#329]
**Describe the bug**
failed building project with error "could not find...". more info in screenshots

**To Reproduce**
1. try to build project with chimera
2. see error

**Expected behavior**
successful build

**Screenshots**
![image](https://user-images.githubusercontent.com/71902968/139914281-48dbf802-cbd6-44d7-b080-5f21fb57b129.png)

**Environment (please complete the following information):**
 - Java Version -16
 - Platform - Paper
 - Platform Version - 1.1.12
 - Chimera Version - 5.0.0

**Additional context**
tried to downloads two files: satisfactory and utilitary

when clicking on any link, a 404 error is returned

**Comment by Pante** [comment]
The error message stems from Gradle trying to find those dependencies in the same repository. Just to confirm, are you trying to build a project that depends on Chimera, or build Chimera? 

If it’s the first, it shouldn’t require Utiltiary & Satisfactory since they’re already shaded into Typist.

If it’s the latter and judging by the error message, you probably didn’t include the correct [Maven repository](https://github.com/Pante/elementary#maven-repository) as utilitary and satisfactory are hosted in a different repository from Chimera.

**Comment by StepanovIgorS** [comment]
I trying to run task build, but get error. Two days ago, it works succefully (p.s sorry for my english)

My build.gradle.kts and settings.gradle.kts:
![Screenshot_1](https://user-images.githubusercontent.com/71902968/140041225-537c9bff-4195-4195-ab4a-e4d3cc134666.png)
![Screenshot_2](https://user-images.githubusercontent.com/71902968/140041242-634cefc1-6c19-47ac-8424-70c025e5796e.png)


![Screenshot_3](https://user-images.githubusercontent.com/71902968/140041257-ea76645c-18b5-457d-a03d-6f6c26aa22cf.png)

**Comment by Pante** [comment]
Seems like I found the issue, it turns out I included maven-shade for all the projects except `Typist`.
![](https://c.tenor.com/otBqQicL6qUAAAAC/doh-homer.gif)

I've deploy a fix to stable, please remove your cached version of Typist and try again. Do let me know if the issue persists. Thanks for taking the time to report the issue!

**Comment by StepanovIgorS** [comment]
Thank you, it works! But I have one question. I wrote command, but when I trying to use argument on russian language or use special symbol, I get error: 

![image](https://user-images.githubusercontent.com/71902968/140231051-71f966fb-74cc-481f-8188-4d3d7331db0e.png)

How to fix this problem? When I trying to test this on CommandExecutor (without chimera) I don't get any errors.

**Comment by Pante** [comment]
Could you post your code please? Internally both Chimera and Spigot/Paper uses Brigadier to parse commands so there shouldn’t be a difference.

**Comment by StepanovIgorS** [comment]
![image](https://user-images.githubusercontent.com/71902968/140295741-ee6f053e-e8df-4ea7-a561-850b4e72a585.png)
![image](https://user-images.githubusercontent.com/71902968/140295783-0bd22341-3f7e-46bf-9148-5613fcb55ad4.png)
![image](https://user-images.githubusercontent.com/71902968/140295807-30fb5616-d448-4d42-b9ef-e8bb84d56055.png)

**Comment by Pante** [comment]
I'll be honest, I have no clue, sorry.

**Comment by andreypfau** [comment]
#russianlivesmatter

**Comment by Pante** [comment]
> 
> 
> Thank you, it works! But I have one question. I wrote command, but when I trying to use argument on russian language or use special symbol, I get error:
> 
> ![image](https://user-images.githubusercontent.com/71902968/140231051-71f966fb-74cc-481f-8188-4d3d7331db0e.png)
> 
> How to fix this problem? When I trying to test this on CommandExecutor (without chimera) I don't get any errors.

Could you add the following information?
* What exactly did you type to get the error?
* What was the expected format? i.e. `/my-command <arg1> <arg2>`
* What was the expected result?

On another note, please copy & paste the code, and surround it in \```<my code here>\```, it's hard to read from the images.

**Comment by StepanovIgorS** [comment]
1) I entered russian symbols or special symbols.
2) /prefix <arg>
3) I shouldn't have gotten the error (see more info in code below)

code:
```
package ru.plugin.prefixes

import com.karuslabs.commons.command.OptionalContext
import com.karuslabs.commons.command.dispatcher.Dispatcher
import com.karuslabs.commons.command.tree.nodes.Argument
import com.karuslabs.commons.command.tree.nodes.Literal
import com.karuslabs.commons.command.types.PlayersType
import com.karuslabs.typist.annotations.Bind
import com.karuslabs.typist.annotations.Command
import com.karuslabs.typist.annotations.Let
import com.karuslabs.typist.annotations.Pack
import com.mojang.brigadier.arguments.StringArgumentType
import com.mojang.brigadier.context.CommandContext
import com.mojang.brigadier.suggestion.SuggestionProvider
import net.kyori.adventure.text.Component
import net.kyori.adventure.text.TextComponent
import net.kyori.adventure.text.format.NamedTextColor
import org.bukkit.Bukkit
import org.bukkit.command.CommandExecutor
import org.bukkit.command.CommandSender
import org.bukkit.entity.Player
import org.jetbrains.exposed.sql.transactions.transaction
import java.util.function.Consumer

object PrefixCommand {
    fun initialize() {
        val player = Argument.of("player", PlayersType())
            .requires { it.hasPermission("Prefixes.canGivePrefixToOthers") }
            .executes { context ->
                val player = context.source as? Player ?: return@executes 0
                val rawOtherPlayer = context.getArgument("player", String::class.java)
                val otherPlayer: Player? = Bukkit.getPlayer(rawOtherPlayer)
                if (otherPlayer == null) {
                    player.sendMessage("Пользователь не найден")
                    return@executes 1
                }
                if (!otherPlayer.isOnline) {
                    player.sendMessage("Пользователь не в сети!")
                }
                Base.newConnection
                transaction {
                    val pref = Prefix.find { Prefixes.UUID eq otherPlayer.uniqueId.toString() }
                    val argumentPrefix = context.getArgument("prefix", String::class.java)
                    if (!pref.empty()) {
                        pref.first().prefix = argumentPrefix
                    } else {
                        Prefix.new {
                            UUID = otherPlayer.uniqueId.toString()
                            prefix = argumentPrefix
                        }
                    }
                    otherPlayer.displayName(Text.text("$argumentPrefix ${otherPlayer.name}"))
                    otherPlayer.playerListName(Text.text("$argumentPrefix ${otherPlayer.name}"))
                    commit()
                }
                player.sendMessage("Вы успешно изменили префикс пользователю ${otherPlayer.name}")
                otherPlayer.sendMessage("Вам был изменён префикс!")
                return@executes 1
            }.build()
        val prefixArgument = Argument.of("prefix", StringArgumentType.word())
            .executes { context ->
                val player = context.source as? Player ?: return@executes 0
                val argumentPrefix = context.getArgument("prefix", String::class.java)
                Base.newConnection
                transaction {
                    val pref = Prefix.find { Prefixes.UUID eq player.uniqueId.toString() }
                    if (!pref.empty()) {
                        pref.first().prefix = argumentPrefix
                    } else {
                        Prefix.new {
                            UUID = player.uniqueId.toString()
                            prefix = argumentPrefix
                        }
                    }
                }
                player.displayName(Text.text("$argumentPrefix ${player.name}"))
                player.playerListName(Text.text("$argumentPrefix ${player.name}"))
                player.sendMessage("Вы успешно изменили себе префикс")
                return@executes 1
            }.then(player).suggests { context, builder ->
                builder.suggest("Топчик").buildFuture()
            }

        val prefix = Literal.of("prefix")
            .requires {
                it.hasPermission("Prefixes.prefix")
            }.executes { context ->
                context.source.sendMessage(Text.text("Использование: /prefix prefix", NamedTextColor.RED))
                return@executes 1
            }.then(prefixArgument).build()

        val dispatcher = Dispatcher.of(plugin)
        dispatcher.root.addChild(prefix)
        dispatcher.update()
    }
}

operator fun Component.plus(component: Component) = append(component)

```

**Comment by Pante** [comment]
From a glance, there doesn't seem to be an issue with the code snippet proven which means that it's probably parsing issue with Brigadier or `PlayersType`.

The information you have provided is far to vague to pinpoint the issue, "I entered russian symbols or special symbols." doesn't really answer the question as we need a _concrete_ example of the how the command was invoked to trigger the unexpected behaviour, i.e. `/prefix <my-prefix> <players>`

**Comment by StepanovIgorS** [comment]
when I don't use special symbols or russian symbols IT WORKS but when I use russian symbols or special symbols! command works without errors when I don't use russian or special symbols (because unfortunately, I live in russia, that many players are live in russia too).

**Comment by Pante** [comment]
To re-iterate, it is extremely difficult to pinpoint, let alone reproduce the issue on our side if no sample input is provided. "I entered Russian symbols or special symbols." does not help us to pinpoint the issue. We need to know _exactly_ what to input to trigger the error, in the form of an example. In addition, does it affect a specific argument, i.e. `prefixArgument` or `player`? Or does it cause the error regardless of where the special characters are used? 

If no such example is provided, it is exceedingly difficult to make any progress on the issue.

**Comment by StepanovIgorS** [comment]
try to enter "/prefix топчик" or "/prefix &7kdkd". You get error. And try to enter "/prefix test" - you don't get error (you have to rewrite my code because I use connection to database).

**Comment by Pante** [comment]
After some investigation, it seems like I found the issue. 

`prefixArgument` uses Brigadier's `StringArgumentType.word()` to parse strings. If we look at `StringArgumentType.word()`'s implementation:
```java
    @Override
    public String parse(final StringReader reader) throws CommandSyntaxException {
        if (type == StringType.GREEDY_PHRASE) {
            final String text = reader.getRemaining();
            reader.setCursor(reader.getTotalLength());
            return text;
        } else if (type == StringType.SINGLE_WORD) {
            return reader.readUnquotedString(); // <-- calls this
        } else {
            return reader.readString();
        }
    }
    
    // Somewhere inside reader.readUnquotedString(), it calls
    public static boolean isAllowedInUnquotedString(final char c) {
        return c >= '0' && c <= '9'
            || c >= 'A' && c <= 'Z'
            || c >= 'a' && c <= 'z'
            || c == '_' || c == '-'
            || c == '.' || c == '+';
    }
```

This is honestly kind of silly and fundamentally broken since it only supports ASCII characters. Moving forward, I'll open an issue regarding this on Brigadier's repository. In the interim, I'll implement a custom `ArgumentType` in Chimera that supports non-ASCII word arguments.

**Comment by Pante** [comment]
I've released 5.1.0 that addresses the issue. Please use `WordType.word()` instead of `StringArgumentType.word()`. One downside of this is that special characters in a string argument will cause the text to turn red on the client since Brigadier doesn't natively support this. Unfortunately there's nothing that can be done on our side to resolve that. I've created an issue in Brigadier's repository to track that.

Do let re-open this issue if the problem persists.

**Comment by StepanovIgorS** [comment]
After update, I get error:

![image](https://user-images.githubusercontent.com/71902968/140648022-4009a08c-7795-484d-8970-2f716014c173.png)

**Comment by Pante** [comment]
Whoops, forgot to add `maven-shade` to plugin once again, I've redeployed 5.1.0 which should be available shortly.

**Comment by StepanovIgorS** [comment]
error didn't fixed before your commit:

![image](https://user-images.githubusercontent.com/71902968/140651072-881eaee2-7b53-4069-b41f-a3b2d867c700.png)

**Comment by Pante** [comment]
I've just re-checked the maven repository and it does contain the shaded jar. Invalidate your local maven repository and try again.
