### ISSUE TITLE
any chance to make the project multi-version?

### ISSUE THREAD

**Issue by portlek** [Pante/chimera#348]
at least 1.13-∞

**Comment by Pante** [comment]
I guess, it'll really depends. It's going to be difficult/tedious to provide backwards compatibility with all prior versions until 1.13 at this point. I won't say it's off the table but I personally don't have the motivation to do so in the near future. 

That said, if someone's kind enough to contribute a PR that does so, I'll be more than happy to merge it!

**Comment by portlek** [comment]
the project definitely needs a design change for both nms modules and reflection things. i agree the point that will take a lot of time to achieve that.

**Comment by Pante** [comment]
Honestly, if/when I get around to adding multi-version support, it'll be by building against Paper.
