### ISSUE TITLE
Commands.java generation

### ISSUE THREAD

**Issue by wiselder** [Pante/chimera#369]
Hi! I use Gradle and import the library using compileOnly.
I'm running compileJava/jar for my plugin, but the Commands.java is not generated. 
What could be the problem? What is the best/true way to generate a class for Gradle?

My code https://gist.github.com/wiselder/2dc3f56ebd0a42cc73747ec294e8f5ad

**Comment by Pante** [comment]
The command looks good to me, maybe it’s a Gradle configuration issue. Could you post your build.gradle?

**Comment by Pante** [comment]
I'm closing this issue for now, please do re-open it if you're still facing the same issue
