### ISSUE TITLE
[BUG] Non-existent method

### ISSUE THREAD

**Issue by ObcbO** [Pante/chimera#502]
[Wiki - Using Chimera Commands#registering-a-command](https://github.com/Pante/Chimera/wiki/using-chimera-commands#registering-a-command)
where, `Commands.of` seems to be non-existent

**Comment by Pante** [comment]
`Commands.of(...)` is part of the code automatically generated by the `typist` module. See https://github.com/Pante/Chimera/wiki/creating-commands-using-annotations. You don't require it if you're not using annotations/code generation. If you are using `typist`, try building the project once first. It sometimes doesn't appear until you do so.

**Comment by ObcbO** [comment]
> `Commands.of(...)`是模块自动生成的代码的一部分。请参阅 https://github.com/Pante/Chimera/wiki/creating-commands-using-annotations。如果不使用注释/代码生成，则不需要它。如果您正在使用 ，请先尝试生成一次项目。它有时直到您这样做才会出现。`typist``typist`

If I build it will tell me it can't find this symbol.
Is there something wrong with my gradle configuration?
```gradle
dependencies {
    ......

    implementation "com.mojang:brigadier:1.0.17"
    compileOnly "com.karuslabs:commons:5.1.0"
    implementation "com.karuslabs:typist:5.1.0"
}
```

**Comment by Pante** [comment]
A few things:
* Did you specify the location of the generated file using `@Pack`?
* Did you import the generated file?

**Comment by ObcbO** [comment]
> * import the generated file

Sorry, how to import the generated file?

**Comment by Pante** [comment]
The generated file is a normal Java file, you need to import it like any other file, i.e. “import my.package.Commands”.

The location of the generated file depends on the @Pack annotation. 

If you’re using an IDE, it should suggest the file. If not, you might need to build the project first before it appears.
